-- 코드를 입력하세요
SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS, ROUND(AVG(b.REVIEW_SCORE),2) as SCORE
FROM REST_INFO as a join REST_REVIEW as b
ON a.REST_ID = b.REST_ID
GROUP BY a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.ADDRESS
HAVING SUBSTRING_INDEX(a.ADDRESS, ' ', 1) IN ('서울시', '서울특별시')
ORDER BY SCORE DESC, a.FAVORITES DESC